---
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: ubuntu-14
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
    attributes:
      apt:
        confd:
          install_recommends: false

  - name: ubuntu-16
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
    attributes:
      apt:
        confd:
          install_recommends: false

suites:
  - name: default12
    driver:
      chef_version: 12.21.3
    run_list:
      - recipe[elasticsearch-curator::default]
      - recipe[elasticsearch-curator-test::default]
    attributes:
      kapacitor:
        ignore_version: false
        setup_repository: true

  - name: default13
    driver:
      chef_version: 13.2.20
    run_list:
      - recipe[elasticsearch-curator::default]
      - recipe[elasticsearch-curator-test::default]
    attributes:
      kapacitor:
        ignore_version: false
        setup_repository: true
