dist: trusty
sudo: false

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk=2.1.11-1

language: ruby
cache:
  directories:
  - vendor/bundle
  - vendor/cookbooks
bundler_args: --without integration --path=$PWD/vendor/bundle
rvm:
  - 2.2
script:
  - chef exec cookstyle
  - chef exec foodcritic --progress -f any .
