dist: trusty
sudo: false

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk=2.1.11-1

language: ruby
cache:
  directories:
  - vendor/bundle
  - vendor/cookbooks
bundler_args: --path=$PWD/vendor/bundle
rvm:
  - 2.2
script:
  - chef exec cookstyle
  - chef exec foodcritic --progress -f any .

services: docker
env:
  matrix:
    - INSTANCE=default12-ubuntu-14
    - INSTANCE=default13-ubuntu-14

script:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
  - cat .kitchen/logs/kitchen.log

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
